[from-internal]

; =========================================================
; RTP BASELINE
; =========================================================

exten => 6001,1,Dial(PJSIP/6001,30)
 same => n,Hangup()

exten => 6002,1,Dial(PJSIP/6002,30)
 same => n,Hangup()


; =========================================================
; SRTP + TLS
; =========================================================

exten => 7001,1,Dial(PJSIP/7001,30)
 same => n,Hangup()

exten => 7002,1,Dial(PJSIP/7002,30)
 same => n,Hangup()